//! # D-Bus interface proxy for: `ma124.mawm.Mawm1`
//!
//! This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
//! Source: `Interface '/ma124/mawm/Mawm' from service 'ma124.mawm.Mawm' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "ma124.mawm.Mawm1",
    default_service = "ma124.mawm.Mawm",
    default_path = "/ma124/mawm/Mawm"
)]
pub trait Mawm1 {
    /// Update signal
    #[zbus(signal)]
    fn update(&self) -> zbus::Result<()>;

    /// FocusedTags property
    #[zbus(property)]
    fn focused_tags(&self) -> zbus::Result<u64>;

    /// FocusedWindowTitle property
    #[zbus(property)]
    fn focused_window_title(&self) -> zbus::Result<String>;

    /// LenTags property
    #[zbus(property)]
    fn len_tags(&self) -> zbus::Result<u64>;

    /// OccupiedTags property
    #[zbus(property)]
    fn occupied_tags(&self) -> zbus::Result<u64>;
}
